### ISSUE TITLE
Find page throws exception after adding waste with unit picker

### ISSUE THREAD

**Issue by ErlendLandro** [ErlendLandro/WasteTrader#40]
```
System.Exception: ScErrDataBindingForJsonException (SCERR14012): An exception occurred when a databinding for a property in json was used. Property 'Amount' in 'MasterPage.FindPage.WasteEntries.WasteEntry'.
Version: 2.3.1.6633.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14012.
   at lambda_method(Closure , Json )
   at Starcounter.Templates.Property`1.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 214
   at Starcounter.Json.SetBoundValuesInTuple() in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 432
   at Starcounter.Json.RetriableSetBoundValues(Boolean retryOnError) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 405
   at Starcounter.Json.<>c__DisplayClass128_0.<ScopeAndSetBoundValuesInTuple>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 378
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 67
   at Starcounter.Templates.TObjArr.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Templates\TObjArr.cs:line 162
   at Starcounter.Json.SetBoundValuesInTuple() in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 432
   at Starcounter.Json.RetriableSetBoundValues(Boolean retryOnError) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 399
   at Starcounter.Json.<>c__DisplayClass128_0.<ScopeAndSetBoundValuesInTuple>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 378
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 67
   at Starcounter.Templates.TObject.CheckAndSetBoundValue(Json parent, Boolean addToChangeLog) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Templates\TObject.cs:line 116
   at Starcounter.Json.CheckOneTemplate(Json parent, TValue template, ChangeLog changeLog) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 341
   at Starcounter.Json.CollectChanges(ChangeLog changeLog) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 242
   at Starcounter.Json.RetriableCollectChanges(ChangeLog changeLog, Boolean retryOnError) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 217
   at Starcounter.Json.<>c__DisplayClass123_0.<ScopeAndCollectChanges>b__0() in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.Object.ChangeLog.cs:line 198
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:line 67
   at Starcounter.XSON.ChangeLog.Generate(Boolean flushLog, Change[]& changeArr) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\ChangeLog.cs:line 100
   at Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 117
   at Starcounter.Internal.JsonMimeConverter.Convert(Request request, IResource before, MimeType mimeType, MimeType& resultingMimeType) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:line 18
   at Starcounter.Json.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Class Json\Json.IResource.cs:line 45
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.Internal\Http\Response.cs:line 809
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 810
Data {
IsRethrown=True
}
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14012
---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WasteTrader.Measurements.MeasurementReader.Read(UnitType unit, Int64 quantity, Int32 unitMetricPrefixPower) in C:\Users\Erlend\Documents\GitHub\WasteTraderMaterial\src\WasteTrader\Measurements\MeasurementReader.cs:line 25
   at WasteTrader.ViewModels.WasteEntry.get_Amount() in C:\Users\Erlend\Documents\GitHub\WasteTraderMaterial\src\WasteTrader\ViewModels\WasteEntry.json.cs:line 11
   at lambda_method(Closure , Json )
HResult=-2146232969
```

**Comment by ErlendLandro** [comment]
It was an issue with an old database. Works after clearing it.
